package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hello-world",
    srcs = [
        "hello-world.cpp",
    ],
    deps = [
        "//a:a",
        "//b:b",
        "//c:c"
    ]
)
